spring:
  application:
    name: smartgrowtent

  datasource:
    url: jdbc:mysql://192.168.1.44:3306/smartgrowdb
    username: smartgrow
    password: 102030
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html