
services:
  mysql:
    image: hypriot/rpi-mysql
    container_name: smartGrowMysql
    restart: always
    environment:
      MYSQL_DATABASE: smartgrowdb
      MYSQL_USER: smartgrow
      MYSQL_PASSWORD: '102030'
      MYSQL_ROOT_PASSWORD: '102030'
      TZ: America/Sao_Paul
    ports:
      - '3306:3306'
    volumes:
      - smartGrowMysqlVol:/var/lib/mysql
    networks:
      - localnet

  smartGrowApp:
    image: vljubovic/ignite:2.14.0-jdk17-4
    container_name: smartGrowApp
    restart: always
    depends_on:
      - mysql
    ports:
      - '8080:8080'  # Certifique-se de que a porta corresponde à porta exposta pela sua aplicação
    volumes:
      - ./smartgrowtent-0.0.1-SNAPSHOT.jar:/app/smartgrowtent-0.0.1-SNAPSHOT.jar
    command: [ "java", "-jar", "/app/smartgrowtent-0.0.1-SNAPSHOT.jar" ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://smartGrowMysql:3306/smartgrowdb
      SPRING_DATASOURCE_USERNAME: smartgrow
      SPRING_DATASOURCE_PASSWORD: '102030'
      TZ: America/Sao_Paulo
    networks:
      - localnet

networks:
  localnet:
    driver: bridge

volumes:
  smartGrowMysqlVol:
    external: true
